CREATE TABLE comments (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          article_id UUID NOT NULL,
                          author_id UUID NOT NULL,
                          body TEXT NOT NULL,
                          created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                          updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                          CONSTRAINT fk_comments_article
                              FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE,
                          CONSTRAINT fk_comments_author
                              FOREIGN KEY (author_id) REFERENCES users(id),
                          CONSTRAINT ck_comments_body
                              CHECK (btrim(body) <> '' AND char_length(body) <= 5000)
);

CREATE INDEX ix_comments_article_created_id
    ON comments(article_id, created_at DESC, id DESC);

CREATE INDEX ix_comments_author_id ON comments(author_id);